import { useEffect, useMemo, useState } from 'react';
import api from '../api/axios';
import NotificationCard from './NotificationCard';
import NotificationSettings from './NotificationSettings';

export default function NotificationCenter() {
  const [data, setData] = useState({ notifications: [], unreadCount: 0 }); const [preferences, setPreferences] = useState(null); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('all'); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const [notifications, prefs] = await Promise.all([api.get('/notifications'), api.get('/notifications/preferences')]); setData(notifications.data); setPreferences(prefs.data.preferences); setError(''); } catch { setError('Could not load notifications.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const items = useMemo(() => data.notifications.filter((item) => (filter === 'all' || (filter === 'unread' ? !item.read : item.priority === filter)) && `${item.title} ${item.description}`.toLowerCase().includes(search.toLowerCase())), [data, filter, search]);
  async function run(action) { try { await action(); setError(''); await load(); } catch { setError('Could not update notifications. Please try again.'); } }
  async function markRead(id) { return run(() => api.patch(`/notifications/${id}/read`)); } async function remove(id) { return run(() => api.delete(`/notifications/${id}`)); }
  async function markAll() { return run(() => api.patch('/notifications/read-all')); } async function test() { return run(() => api.post('/notifications/test')); }
  async function updatePreference(key, value) { try { const { data: response } = await api.patch('/notifications/preferences', { [key]: value }); setPreferences(response.preferences); setError(''); } catch { setError('Could not update notification settings. Please try again.'); } }
  return <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_260px] gap-6"><section className="border border-hairline rounded-xl p-5 card-surface" aria-busy={loading}><div className="flex flex-wrap justify-between gap-3"><div><p className="font-mono text-xs text-ledger-light uppercase">Smart notifications</p><h1 className="font-display text-3xl text-bone">Stay ahead of your money</h1></div><div className="flex gap-2"><button onClick={test} className="rounded-xl border border-hairline px-3 py-2 font-mono text-xs text-bone">Test</button><button onClick={markAll} className="rounded-xl bg-ledger px-3 py-2 font-display text-xs text-white">Mark all read</button></div></div><div className="mt-5 flex flex-wrap gap-2"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search notifications" aria-label="Search notifications" className="min-w-0 flex-1 rounded-xl border border-hairline bg-ink/80 px-3 py-2 text-sm text-bone" /><select value={filter} onChange={(event) => setFilter(event.target.value)} aria-label="Filter notifications" className="rounded-xl border border-hairline bg-ink/80 px-2 text-sm text-bone"><option value="all">All</option><option value="unread">Unread</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div>{error && <p role="alert" className="text-signal text-sm mt-3">{error}</p>}<p className="font-mono text-xs text-bone/65 mt-4">{data.unreadCount} unread</p><div className="mt-3 space-y-3">{loading ? <p className="font-body text-sm text-bone/65 py-6 text-center">Loading notifications…</p> : items.length ? items.map((item) => <NotificationCard key={item.id} notification={item} onRead={markRead} onDelete={remove} />) : <p className="font-body text-sm text-bone/65 py-6 text-center">No notifications match this filter.</p>}</div></section><NotificationSettings preferences={preferences} onChange={updatePreference} /></div>;
}
